export const IMAGE_TYPES = {
  ADD_IMAGE_TO_CARD: 'IMAGE_TYPES.ADD_IMAGE_TO_CARD',
  DELETE_IMAGE: 'IMAGE_TYPES.DELETE_IMAGE',
  GET_IMAGES:'IMAGE_TYPES.GET_IMAGES',
  SET_LOADING:'IMAGE_TYPES.SET_LOADING',
  GET_FILTERS:'IMAGE_TYPES.GET_FILTERS',
  GET_FEATURED:'IMAGE_TYPES.GET_FEATURED',
  SET_ITEM_TO_BADGE:'IMAGE_TYPES.SET_ITEM_TO_BADGE',
  TOGGLE_BADGE_MENU:'IMAGE_TYPES.TOGGLE_BADGE_MENU',
  CLEAR_BADGE:'IMAGE_TYPES.CLEAR_BADGE',
}